Source/Web/TestManagmentSystem.Web/Areas/Tests/Controllers/TestScenariosController.cs
namespace TestManagmentSystem.Web.Areas.Tests.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using TestManagmentSystem.Data.Models;
    using TestManagmentSystem.Data.UnitOfWork;
    using TestManagmentSystem.Web.Areas.Tests.Infrastructure.Services.Contracts;
    using TestManagmentSystem.Web.Areas.Tests.InputModels;
    using TestManagmentSystem.Web.Areas.Tests.ViewModels;
    using TestManagmentSystem.Web.Controllers;
    using TestManagmentSystem.Web.Infrastructure;

    [Authorize]
    public class TestScenariosController : BaseController
    {
        private const int ItemsPerPage = 5;
        private readonly ITestScenarioServices testScenarioServices;
        private readonly ISanitizer sanitizer;

        public TestScenariosController(ITestManagmentSystemData data, ITestScenarioServices services, ISanitizer sanitizer)
            : base(data)
        {
            this.sanitizer = sanitizer;
            this.testScenarioServices = services;
        }

        public ActionResult Index(int id = 1)
        {
            return View(id);
        }

        [OutputCache(Duration = 5 * 1)]
        public ActionResult AllScenarios(int? page = 1, string searchPattern = "")
        {
            int numberOfPages = 1;
            var partial = PartialView("_TestScenariosPartial", this.testScenarioServices.GetTestScenarioViewModel(out numberOfPages, ItemsPerPage, page ?? 1));

            TempData["CurrentPage"] = page;
            TempData["ActionLink"] = "/Tests/TestScenarios/Index";
            TempData["NumberOfPages"] = numberOfPages;

            return partial;
        }

        public ActionResult Create ()
        {
            var model = new TestScenarioInputModel();
            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TestScenarioInputModel input)
        {
            if (ModelState.IsValid)
            {
                var scenario = new TestScenario
                    {
                        Name = sanitizer.Sanitize(input.Name),
                        Description = sanitizer.Sanitize(input.Description),
                        Type = input.Type,
                        ProjectId = input.Project,
                        SystemEnvironmentId = input.System
                    };

                this.Data.TestScenarios.Add(scenario);
                this.Data.SaveChanges();
                TempData["NotificationMessage"] = "Test Scenario successfully created";
                return this.RedirectToAction("AllScenarios");
            }

            return this.View(input);
        }
    }
}

Source/Web/TestManagmentSystem.Web/Views/Shared/_Layout.cshtml
@using TestManagmentSystem.Common;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/kendo")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/custom")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Systems", "Index", "Systems", new { area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Issues", "Index", "Issues", new { area = string.Empty }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            Tests Management
                            <ul>
                                <li>@Html.ActionLink("Test Scenarios", "Index", "TestScenarios", new { area = "Tests" }, null)</li>
                                @*<li>@Html.ActionLink("Issues", "Index", "Issues", new { area = "Tests" }, null)</li>*@
                            </ul>
                        </li>
                        if (User.IsInRole(GlobalConstants.AdminRole))
                        {
                            <li>
                                Administration
                                <ul>
                                    <li>@Html.ActionLink("Systems", "Index", "TestedSystems", new { area = "Administration" }, null)</li>
                                    @*@<li>@Html.ActionLink("Projects", "Index", "Projects", new { area = "Administration" }, null)</li>
                                    <li>@Html.ActionLink("Environments", "Index", "Environments", new { area = "Administration" }, null)</li>*@
                                </ul>
                            </li>
                        }
                    }
                </ul>

                            @Html.Partial("_LoginPartial")
</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Test Management System</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $('#menu').kendoMenu();
        })
    </script>
</body>
</html>

Source/Web/TestManagmentSystem.Web/Views/Shared/_PagingPartial.cshtml
@using TestManagmentSystem.Web.ViewModels;
@model PagingViewModel
<div class="row text-center">
    <ul class="pagination">
        @if(@Model.CurrentPage > 1)
        {
        <li><a href=@(Model.ActionLink + "/" + (Model.CurrentPage-1))><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        }
        @for (var i = 1; i <= Model.NumberOfPages; i++)
        {
            var state = "";
            if (i == Model.CurrentPage)
            {
                state = "active";
            }
            <li class=@state>

                <a href=@(Model.ActionLink + "/" + i)>@i</a>
            </li>
        }
        @if(@Model.CurrentPage < @Model.NumberOfPages)
        {
        <li><a href=@(Model.ActionLink + "/" + (Model.CurrentPage+1))><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        }
    </ul>
</div>